### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by syo-tokeshi** [syo-tokeshi/method-quiz#14]
# ペーパープロトタイプ

https://bootcamp.fjord.jp/products/16181

# リソース

| Method | Path                  | Description                                                                                                                                                                          | 
| ------ | --------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | 
| GET    | /                     | トップ画面を表示（ログインしていればメソッドの一覧画面`/methods`に遷移、ログインしていなければトップページを表示する）<br>こちらのページから、omniauthを利用し、GitHub認証登録・ログインを実装する | 
| GET    | /methods              | メソッドの一覧画面                                                                                                                                                                   | 
| POST   | /methods              | メソッドの新規登録                                                                                                                                                                   | 
| GET    | /methods/new          | メソッドの新規登録画面                                                                                                                                                               | 
| GET    | /methods/id/edit      | メソッドの編集画面                                                                                                                                                                   | 
| PATCH  | /methods/id           | メソッドの更新                                                                                                                                                                       | 
| DELETE | /methods/id           | メソッドの削除                                                                                                                                                                       | 
| GET    | /quiz/new             | クイズの設定画面                                                                                                                                                                     | 
| POST   | /quiz                 | クイズの新規作成(DB上のリソースは作らない)                                                                                                                                           | 
| GET    | /quiz                 | 一つ一つのクイズ(クイズはDBでリソースを作らないので、idを持たない。毎回ランダムで作成される)                                                                                         | 
| POST   | /auth/github/callback | GitHub認証。登録・ログインを処理する                                                                                                                                                 | 
| GET    | /me                   | ユーザーのプロフィールを表示                                                                                                                                                         | 
| DELETE | /logout               | ログアウトの実行                                                                                                                                                                     | 
| DELETE | /retirement           | 退会処理                                                                                                                                                                             | 

# 説明

このアプリの主な機能は
`methods`と`quiz`です。

## methods

railsの`resources`を使ったRESTfulなapiで作ります。
`GET /methods`以外は、railsの標準的な機能で作るのですが、
`GET /methods`はreactを使って構築する予定です。
railsはデータベースから、ユーザーに紐づいた`methods`の全てを取得し、
reactにデータを渡し、reactはstateで状態管理します

[`/methods`でreactが管理するデータ]
```js
methods = [] // map,each_with_indexみたいのが格納されている。これをmapで展開する
visibility = "all",  // {all: 全て表示、remembered:覚えたものを表示、notRemembered:覚えてないものを表示}のような絞り込みを、reactで行う予定
language = "ruby" // 言語が指定されている場合、reactでこちらも絞り込む(`method.language`にアクセスする事で絞り込める)
page = 0 // ページネーションの何番目にいるか
```

※`vite_rails`を使って、railsからreactにデータを渡し、呼び出します

検索の絞り込みは、reactで管理している値を利用し、リクエストを送らず描画します。

[`/methods`]
![Image](https://github.com/syo-tokeshi/method-quiz/assets/54713809/a503e6df-e08b-4feb-8244-4bfb9fc3f408)

## quiz

クイズは、DB上ではリソースを持ちません。
最初にクイズの設定画面である`/quiz/new`にアクセスし、
ユーザーが設定を入力後、`POST  /quiz`にリクエストを送ります。
その値を利用し、`methods`テーブルから言語に応じたメソッドを一つ取得し、
- name
- operation_detail
- use_case

をboolean(表示・非表示フラグ)で管理した値と合わせて、`GET   /quiz `に渡します。

[`/quiz/new`]
![Image](https://github.com/syo-tokeshi/method-quiz/assets/54713809/3352c836-ccb5-4678-b6f1-23191e41d89d)

### 次のクイズに行く際の説明

次のクイズに行く際は、こちらの写真の右下の「次の問題」というボタンをクリックすると、次のクイズが出題されます。
[`/quiz`]
![Image](https://github.com/syo-tokeshi/method-quiz/assets/54713809/6000c78b-ba7f-4b76-997d-d9bf5f2eac89)

次のクイズを出題するために、

```
name :true
operation_detail :false
use_case :false
language : "ruby"
```
のような値も合わせて、`POST  /quiz`にリクエスト送ります。
この値を利用して、先ほど説明した処理を行います。

ちなみに、URLから`GET  /quiz`を直打ちした場合は、デフォルトで

- データベース上で`remembered`がfalseであるメソッドからランダムで取ってきて、そのメソッド +

```
name :true
operation_detail :false
use_case :false
language : "ruby" # 上の処理で取得したメソッドのlanguageが入る
```

を`GET  /quiz`に渡し、クイズを作成します。

`GET  /quiz`はreactで作成します。
管理するデータは以下です

[`/quiz`でreactが管理するデータ]
```js
method = [] // each_with_index等のメソッドが一つ格納されています
name :true
operation_detail :false
use_case :false
language = "ruby"
```

この値を利用し、
- `remembered`がfalseであるメソッドを、保有している`language`からランダムで取ってくる

というのを繰り返します

**Comment by yuuu** [comment]
@syo-tokeshi 
確認しました 👍 気になった点をいくつかコメントしますね。

- クイズ個別の画面は1つのエンドポイントでReactを用いて、出題→回答を繰り返していくイメージを持ちました
    - 出題するクイズの情報は予めDOMに埋め込んでおくのでしょうか？それともAPIを使ってバックエンドから取得しますか？
- クイズはひたすら `/quiz` へのPOST→GETを繰り返すものなので、終了画面のようなものはない理解であっていますか？
- クイズの画面に「前の問題」というボタンがありますが、どうやって前の問題を表示するのかが気になりました。

**Comment by syo-tokeshi** [comment]
> 出題するクイズの情報は予めDOMに埋め込んでおくのでしょうか？それともAPIを使ってバックエンドから取得しますか？

DOMに埋め込んでおく実装にします🙇‍♂️

`POST  /quiz`にリクエストを送ると、このような値が返却されるので
```
method = [id, user_id, language, name, operation_detail, use_case, remembered] # methodsテーブルのレコードが一つ入る
name :true
operation_detail :false
use_case :false
language : "ruby" 
```
それをそのままstateとしてデータを保有して、ユーザーが「回答をみる」というボタンを押したら表示できるようにします

<img width="602" alt="保存" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/7da73f0b-9746-4281-bbb6-e2f176fa7de9">

[吹き出しの部分は、「回答をみる」のボタンを押すことで、`display none`から`display block`になり、表示される]
<img width="586" alt="保存２" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/6f6ddaca-66ab-4676-b74f-0399863453e7">

**Comment by syo-tokeshi** [comment]
> クイズはひたすら /quiz へのPOST→GETを繰り返すものなので、終了画面のようなものはない理解であっていますか？

はい、その通りです🙇‍♂️

`methods`テーブルから`remembered = false`のレコードが無かったら、この画面を出力させる予定です🙇‍♂️

<img width="720" alt="スクリーンショット 2023-06-23 10 13 17" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/d9717d8f-0dd1-4b2b-a0dd-d449953f5e0a">

**Comment by syo-tokeshi** [comment]
> クイズの画面に「前の問題」というボタンがありますが、どうやって前の問題を表示するのかが気になりました。

ここはyuuuさんにも聞きたいのですが、

- javascriptの`history.back();`メソッドで、`GET /quiz`から直前の`GET /quiz`に戻る

ことが出来ますでしょうか？🙇‍♂️

<img width="851" alt="文字" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/b131dbac-e657-4afa-964b-9d8b154e0649">


もし出来ない場合は、
-  戻るボタンを削除する

で対応しようと思います🙇‍♂️

直前のデータをreactのstate or localStorageで管理する事も可能だと思いましたが、「前の問題」という機能はそこまで欲しくないので、その場合は削除しようと思います🙇‍♂️

**Comment by yuuu** [comment]
`history.back()` で戻ることはできますが、あくまでブラウザの履歴情報を元に前の画面を描画しているだけなので、意図的に履歴を削除されている場合は表示できない(orリロードが発生する)懸念はあります。あと、 `history.back()` するならブラウザの戻るボタンと同じ挙動になるはずなので、ボタンを設置する意味はあまりないかもしれませんね。

**Comment by yuuu** [comment]
`POST  /quiz` について、コメントを見る限り非同期でのリクエストに見えたのですが認識あっていますでしょうか？

もし非同期でのリクエストだとすると以下が気になりました。

- 次の問題をどうやって取得するのか？
- 非同期にする理由は何か？

**Comment by syo-tokeshi** [comment]
> `history.back()` で戻ることはできますが、あくまでブラウザの履歴情報を元に前の画面を描画しているだけなので、意図的に履歴を削除されている場合は表示できない(orリロードが発生する)懸念はあります。あと、 `history.back()` するならブラウザの戻るボタンと同じ挙動になるはずなので、ボタンを設置する意味はあまりないかもしれませんね。

了解しました。
色々考えた結果、戻るボタンはある意味が無さそうだと思うので削る事にします🙇‍♂️

回答ありがとうございました😄

**Comment by syo-tokeshi** [comment]
> POST  /quiz について、コメントを見る限り非同期でのリクエストに見えたのですが認識あっていますでしょうか？

すみませ、URL設計を見直し、`POST  /quiz`を廃止し、以下の二つのURIで、クイズ機能を作るよう、変更します

| GET | /quiz/new | クイズの設定画面                                                                                                                                       | 
| --- | --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------ | 
| GET | /quiz     | 一つのクイズを新規作成し、HTMLファイルを返却。<br>クイズはDBでリソースを作らないので、idを持たない。毎回ランダムで作成される | 

処理としては同期処理にし、以下のようなプログラムが走るようにします🙇‍♂️

```rb
def quiz
    @language = params[:language]
    @name = params[:name] || true
    @operation_detail = params[:operation_detail] || false
    @use_case = params[:use_case] || false
    if @language
      @method = Methods.where(user_id: current_user.id, remembered: false, language: @language).sample
    else
      @method = Methods.where(user_id: current_user.id, remembered: false).sample
    end
  end
```

このようなコントローラーの設定にすると、
- URLに直打ちで`/quiz`にアクセスした場合
- リロードした場合
に対応できると考えております🙇‍♂️

**Comment by yuuu** [comment]
回答ありがとうございます。
`GET /quiz` にアクセスすればクイズが表示され、リロードすればランダムに問題が変わる、という仕様にするということですね。

その場合、今度は「覚えた！」をどうやってDBに反映するかが問題になりそうですが何か策はありますでしょうか？
また、クイズが完了した後の「再度クイズに挑戦」についても、どうやって「全てのクイズを覚えた状態」からリセットするのかが気になりました。

**Comment by syo-tokeshi** [comment]
@yuuu 
> その場合、今度は「覚えた！」をどうやってDBに反映するかが問題になりそうですが何か策はありますでしょうか？

クイズを出題する際、react側では以下のようなデータを保有しております。
```rb
method = [id, user_id, language, name, operation_detail, use_case, remembered] # methodsテーブルのレコードが一つ入る
name :true
operation_detail :false
use_case :false
language : "ruby" 
```

methodが持っているidを利用して、
以下のようにリクエストを送ります

https://github.com/fjordllc/bootcamp/blob/324ddb7b53af5fbb7b531cb3c42dcc08a8eece2d/app/javascript/components/Tags/TagEditModal.jsx#L23

```jsx
const updateMethod = () => {
    fetch(`/methods/${method.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
        'X-Requested-With': 'XMLHttpRequest',
        'X-CSRF-Token': CSRF.getToken()
      },
      credentials: 'same-origin',
      redirect: 'manual',
      body: JSON.stringify({ method: { remembered: true } })
    })
      .then(() => {
        toast.methods.toast('メソッドを「覚えた」に移動させました')
        updateTagList()
      })
      .catch((error) => {
        console.warn(error)
      })
  }
  ```
それにより、メソッドを「覚えた！」に移動させることが可能になります🙇‍♂️

**Comment by syo-tokeshi** [comment]
> また、クイズが完了した後の「再度クイズに挑戦」についても、どうやって「全てのクイズを覚えた状態」からリセットするのかが気になりました。

はい、こちらに関して、まずクイズが出題される条件を提示します。

1. languageに関係なく、remembered がfalseであるmethodsテーブルのレコードがあれば良い

です。

なので、

- 「再度クイズに挑戦」ボタン
- ヘッダーの「クイズに挑戦する」ボタン

を、上記の条件を満たしている場合のみ表示します🙇‍♂️
そして、満たしていない場合、`GET /quiz`の画面のリンクを以下に変更します
<img width="605" alt="スクリーンショット 2023-06-26 10 51 51" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/a34bca29-f2e1-49d1-bdac-79fbf7a728b2">

**Comment by yuuu** [comment]
なるほど `PATCH | /methods/id` はAPIとしても実行可能とする設計なのですね 👍 であれば問題なさそうです。

**Comment by syo-tokeshi** [comment]
@yuuu 
お疲れ様です。
DB設計変更に伴って URL(リソース)も設計し直しました🙇‍♂️
ご確認よろしくお願いいたします🙇‍♂️

[routes.rb]
```rb
  resources :user_ruby_methods
  resources :ruby_methods
  resource :ruby_quiz, only: [:new, :show]
```

Method | Path | Description
-- | -- | --
GET | / | トップ画面を表示（ログインしていればメソッドの一覧画面を、ログインしていなければトップページを表示する）こちらのページから、omniauthを利用し、GitHub認証登録・ログインを実装する
GET | /ruby_methods | 管理者用メソッドの一覧画面
POST | /ruby_methods | 管理者用メソッドの新規登録
GET | /ruby_methods/new | 管理者用メソッドの新規登録画面
GET | /ruby_methods/id/edit | 管理者用メソッドの編集画面
PATCH | /ruby_methods/id | 管理者用メソッドの更新
DELETE | /ruby_methods/id | 管理者用メソッドの削除
GET | /user_ruby_methods | 一般ユーザー用メソッドの一覧画面
POST | /user_ruby_methods | 一般ユーザー用メソッドの新規登録
GET | /user_ruby_methods/new | 一般ユーザー用メソッドの新規登録画面
GET | /user_ruby_methods/id/edit | 一般ユーザー用メソッドの編集画面 ※description(メソッドの説明) & rememberedしか更新できないようにします
PATCH | /user_ruby_methods/id | 一般ユーザー用メソッドの更新
DELETE | /user_ruby_methods/id | 一般ユーザー用メソッドの削除
GET | /ruby_quiz/new | クイズの設定画面
GET | /ruby_quiz | 一つのクイズを新規作成し、HTMLファイルを返却。アクションはshowにする。(クイズはDBでリソースを作らないので、idを持たない。毎回ランダムで作成される)
POST | /auth/github/callback | GitHub認証。登録・ログインを処理する
GET | /me | ユーザーのプロフィールを表示
DELETE | /logout | ログアウトの実行
DELETE | /retirement | 退会処理

**Comment by syo-tokeshi** [comment]
## 町田さんと話あった結果の、リソース設計

| Method | Path                       | Description                                                                                                                                                                          | 
| ------ | -------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | 
| GET    | /                          | トップ画面を表示（ログインしていればメソッドの一覧画面を、ログインしていなければトップページを表示する）<br>こちらのページから、omniauthを利用し、GitHub認証登録・ログインを実装する | 
| GET    | /ruby_methods              | 管理者用メソッドの一覧画面                                                                                                                                                           | 
| POST   | /ruby_methods              | 管理者用メソッドの新規登録                                                                                                                                                           | 
| GET    | /ruby_methods/new          | 管理者用メソッドの新規登録画面                                                                                                                                                       | 
| GET    | /ruby_methods/id/edit      | 管理者用メソッドの編集画面                                                                                                                                                           | 
| PATCH  | /ruby_methods/id           | 管理者用メソッドの更新                                                                                                                                                               | 
| DELETE | /ruby_methods/id           | 管理者用メソッドの削除                                                                                                                                                               | 
| GET    | /user_ruby_methods         | 一般ユーザー用メソッドの一覧画面                                                                                                                                                     | 
| POST   | /user_ruby_methods         | 一般ユーザー用メソッドの新規登録                                                                                                                                                     | 
| GET    | /user_ruby_methods/id/edit | 一般ユーザー用メソッドの編集画面 ※description(メソッドの説明) & rememberedしか更新できないようにします                                                                              | 
| PATCH  | /user_ruby_methods/id      | 一般ユーザー用メソッドの更新                                                                                                                                                         | 
| DELETE | /user_ruby_methods/id      | 一般ユーザー用メソッドの削除                                                                                                                                                         | 
| GET    | /ruby_quiz/new             | クイズの設定画面                                                                                                                                                                     | 
| GET    | /ruby_quiz                 | 一つのクイズを新規作成し、HTMLファイルを返却。<br>アクションはshowにする。(クイズはDBでリソースを作らないので、idを持たない。毎回ランダムで作成される)                               | 
| POST   | /auth/github/callback      | GitHub認証。登録・ログインを処理する                                                                                                                                                 | 
| GET    | /me                        | ユーザーのプロフィールを表示                                                                                                                                                         | 
| DELETE | /logout                    | ログアウトの実行                                                                                                                                                                     | 
| DELETE | /retirement                | 退会処理                                                                                                                                                                             |

**Comment by syo-tokeshi** [comment]
また、ユーザーがクイズするメソッドのデータは、seedファイルに記載し、一気に流し込む予定です。

https://github.com/syo-tokeshi/pra-method-quiz/blob/main/db/seeds.rb#L35-L61

サンプル
```rb
def create_url(name)
  category, name = name.split('#')
  if Net::HTTP.get_response(URI.parse("https://docs.ruby-lang.org/ja/latest/method/#{category}/i/#{name}.html")).code == '200'
    "https://docs.ruby-lang.org/ja/latest/method/#{category}/i/#{name}.html"
  else
    "https://docs.ruby-lang.org/ja/latest/class/#{category}.html#I_#{name.upcase.slice(/[^?]+/)}--3F"
  end
end

# res = %w[& * + - << <=> == [] []= | all? any? append assoc at bsearch bsearch_index clear clone collect collect! combination compact compact! concat count cycle delete delete_at delete_if difference dig drop drop_while dup each each_index empty? eql? fetch fill filter filter! find_index first flatten flatten! hash include? index insert inspect intersect? intersection join keep_if last length map map! max min minmax none? one? pack permutation pop prepend product push rassoc reject reject! repeated_combination repeated_permutation replace reverse reverse! reverse_each rindex rotate rotate! sample select select! shift shuffle shuffle! size slice slice! sort sort! sort_by! sum take take_while to_a to_ary to_h to_s transpose union uniq uniq! unshift values_at zip]
# res = %w[& * + - << <=> == [] []= | all? any? append assoc at]
res = %w[children close each each_child fileno inspect path pos pos= read rewind seek tell to_path]
      .map do |item|
  "Dir##{item}"
end

res.each do |name|
  RubyMethod.create([
                      name: name.split('#')[1],
                      category: name.split('#')[0],
                      official_url: create_url(name)
                    ])
end
```

**Comment by yuuu** [comment]
見直しありがとうございます。いくつかコメントします。

- 「一般ユーザー用メソッドの新規登録画面」のURIが漏れてそうです
- クイズの画面で「知っている」「知らない」を選択することで、 `user_ruby_methods` テーブルの `remembered` が更新される認識ですが、POSTまたはPUT用のURIは不要でしょうか？

**Comment by yuuu** [comment]
なるほど。クイズでは予めユーザーがリストアップしたメソッドのみが出題されるのかなと推測していましたが、このシステムに登録されている全メソッドのうち、そのユーザーがまだ覚えていないものが出題される認識で合っていますでしょうか？

**Comment by syo-tokeshi** [comment]
> なるほど。クイズでは予めユーザーがリストアップしたメソッドのみが出題されるのかなと推測していましたが、このシステムに登録されている全メソッドのうち、そのユーザーがまだ覚えていないものが出題される認識で合っていますでしょうか？

クイズに挑戦する条件なのですが、

このような仕様を想定してます

1. 「まだ挑戦してないメソッド」が残っている場合は、ラジオボタンのデフォルトにして、この条件で答えてもらうことにする
1. 「まだ挑戦してないメソッド」が完了した場合は、「まだ挑戦してないメソッド」のラジオボタンが消え、

- 知らないメソッド
- 知っているメソッド

のどちらかを選択してもらって、クイズに挑戦してもらう、という仕様になります🙇‍♂️

<img width="352" alt="スクリーンショット 2023-07-14 9 51 10" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/9432646e-0a1b-4807-a9ff-5f7a2a29917e">

**Comment by yuuu** [comment]
回答ありがとうございます 👍 納得しました。
このリソース設計で大丈夫そうですね！
