### ISSUE TITLE
データ設計

### ISSUE THREAD

**Issue by syo-tokeshi** [syo-tokeshi/method-quiz#22]

**Comment by toke04** [comment]
[初期バージョン]
<img width="845" alt="スクリーンショット 2023-06-26 18 44 33" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/b3a29f51-79c7-4a46-86da-70c6ac2083a1">




# users

| No  | 論理名称   | 物理名称   | データ型 | PK  | UQ  | NN  | 備考            | 
| --- | ---------- | ---------- | -------- | --- | --- | --- | --------------- | 
| 1   | id         | id         | integer  | ○  | ○  | ○  | ユーザーのid    | 
| 2   | ユーザーid | uid        | string   |     | ○  | ○  | Githubのuser_id | 
| 3   | ユーザー名 | name       | string   |     |     | ○  |                 | 
| 4   | 画像url    | avatar_url | string   |     |     | ○  |                 | 
| 5   | 登録日     | created_at | datetime |     |     | ○  |                 | 
| 6   | 更新日     | updated_at | datetime |     |     | ○  |                 | 

# methods

| No  | 論理名称   | 物理名称         | データ型 | PK  | FK  | UQ  | NN  | 備考                                                                                                  | 
| --- | ---------- | ---------------- | -------- | --- | --- | --- | --- | ----------------------------------------------------------------------------------------------------- | 
| 1   | id         | id               | integer  | ○  |     | ○  | ○  |                                                                                                       | 
| 2   | user_id    | user_id          | integer  |     | ○  | ○  | ○  | nameとのユニークな組み合わせにする                                                                    | 
| 3   | 言語       | language         | integer   |     |     |     | ○  | メソッドは、どれかの言語に属する。<br>`languages`テーブルは作らず、<br>選択肢はモデルでenumで持たせる | 
| 4   | メソッド名 | name             | string   |     |     | ○  | ○  | user_idとのユニークな組み合わせにする                                                                 | 
| 5   | 動作内容   | operation_detail | text     |     |     | ○  | ○  |                                                                                                       | 
| 6   | 使用ケース | use_case         | text     |     |     | ○  | ○  |                                                                                                       | 
| 7   | 覚えた     | remembered       | boolean  |     |     |     | ○  | メソッドを覚えたかどうかの管理フラグ                                                                  | 
| 8   | 公式サイトのurl        | official_url     | string   |     |     |     |     | 公式サイトのURLを貼る                                                                                 | 
| 9   | 登録日     | created_at       | datetime |     |     |     | ○  |                                                                                                       | 
| 10  | 更新日     | updated_at       | datetime |     |     |     | ○  |                                                                                                       |

**Comment by yuuu** [comment]
@syo-tokeshi 
確認しました 👍 ミニマムな仕様という意味ではこのテーブル設計で実現できそうです。以下は気になった点です。

- Rubyだとメソッドはクラスに属していますし、同じメソッドでもクラスが変わると仕様も変わりますが、このあたりはどう表現されるのでしょうか？
    - メソッド名に `Array#map` のように入力する想定でしょうか？
    - クラスというテーブルを作るのもアリかもしれません。一方、他言語ではクラスに属さないメソッド(関数)という概念もあるので悩ましいところです。
- 複数のユーザーが同じ名前のメソッドを登録した場合も、DBとしては別のレコードを表す認識であっていますか？
    - だとするとユニークインデックスは `user_id` と `メソッド名` の複合インデックスにする必要がありますね
    - 今回は「やらない」という判断でも良いですが、ユーザー間でメソッドに対して記述した内容を共有できると面白いなーと思いました

**Comment by syo-tokeshi** [comment]
> Rubyだとメソッドはクラスに属していますし、同じメソッドでもクラスが変わると仕様も変わりますが、このあたりはどう表現されるのでしょうか？
メソッド名に Array#map のように入力する想定でしょうか？

はい、ここはユーザーに任せる所なのですが`Array#map`のように入力してもらいたければどうぞ😊、という形にしようと思います🙇‍♂️

メソッドに対して「クラスの選択を必須にする」を導入すると、気楽さが減って良くない気がしました。

例えば、`each_with_index`はクラスではなく、[Enumerableモジュール](https://docs.ruby-lang.org/ja/latest/class/Enumerable.html)で定義されているメソッドですし、メソッドを登録する時に、「これはどこのクラス or モジュールのメソッドか」を意識させると勉強にはなるのですが、登録するのが億劫になる気がするので、ユーザーに任せようと思います🙇‍♂️

https://docs.ruby-lang.org/ja/latest/method/Enumerable/i/each_with_index.html

**Comment by syo-tokeshi** [comment]
> 複数のユーザーが同じ名前のメソッドを登録した場合も、DBとしては別のレコードを表す認識であっていますか？

はい！🙇‍♂️
気づいておりませんでした、、🙇‍♂️
めちゃくちゃ大事ですね、、🙇‍♂️

ユニークインデックスは user_id と メソッド名 の複合インデックスにするようにします🙇‍♂️

> 今回は「やらない」という判断でも良いですが、ユーザー間でメソッドに対して記述した内容を共有できると面白いなーと思いました

はい、実はその機能を、ファーストリリースの後に実装しようと思っています🙇‍♂️

`GET /users/1/methods`のような形でアクセスしたら、ユーザー1の登録したメソッド一覧が確認できて

- このユーザーの登録しているメソッドを、自分のメソッド一覧に登録できる

という機能を作る可能性があります🙇‍♂️

ただ、ファーストリリースでは、基本的にこのままで行こうと思ってます🙇‍♂️

**Comment by syo-tokeshi** [comment]
@yuuu 
お疲れ様です。
methodsテーブルに`url`というカラムを追加します🙇‍♂️

理由とつきまして、
- メソッドを登録する際に、ちゃんと調べて登録したくなるケースを考慮
- クイズの答え合わせの際に、「ホントかよ」と気になった時に、すぐに公式サイトを見に行けるようにしたい

というのを考えまして、追加します🙇‍♂️
<img width="825" alt="スクリーンショット 2023-06-26 18 38 04" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/c551be47-856c-42bf-bea8-ee5a1020e4af">

| No  | 論理名称   | 物理名称         | データ型 | PK  | FK  | UQ  | NN  | 備考                                                                                                  | 
| --- | ---------- | ---------------- | -------- | --- | --- | --- | --- | ----------------------------------------------------------------------------------------------------- | 
| 1   | id         | id               | integer  | ○  |     | ○  | ○  |                                                                                                       | 
| 2   | user_id    | user_id          | integer  |     | ○  | ○  | ○  | nameとのユニークな組み合わせにする                                                                    | 
| 3   | 言語       | language         | string   |     |     |     | ○  | メソッドは、どれかの言語に属する。<br>`languages`テーブルは作らず、<br>選択肢はモデルでenumで持たせる | 
| 4   | メソッド名 | name             | string   |     |     | ○  | ○  | user_idとのユニークな組み合わせにする                                                                 | 
| 5   | 動作内容   | operation_detail | text     |     |     | ○  | ○  |                                                                                                       | 
| 6   | 使用ケース | use_case         | text     |     |     | ○  | ○  |                                                                                                       | 
| 7   | 覚えた     | remembered       | boolean  |     |     |     | ○  | メソッドを覚えたかどうかの管理フラグ                                                                  | 
| 8   | url        | url              | string   |     |     |     |   | 公式サイトのURLを貼る                                                                                 | 
| 9   | 登録日     | created_at       | datetime |     |     |     | ○  |                                                                                                       | 
| 10  | 更新日     | updated_at       | datetime |     |     |     | ○  |                                                                                                       |

**Comment by syo-tokeshi** [comment]
お疲れ様です。
methodsテーブルにcategory というカラムを追加したいです🙇‍♂️
以下でよろしいでしょうか？

| No  | 論理名称        | 物理名称         | データ型 | PK  | FK  | UQ  | NN  | 備考                                                                                                                                       | 
| --- | --------------- | ---------------- | -------- | --- | --- | --- | --- | ------------------------------------------------------------------------------------------------------------------------------------------ | 
| 1   | id              | id               | integer  | ○  |     | ○  | ○  |                                                                                                                                            | 
| 2   | user_id         | user_id          | integer  |     | ○  | ○  | ○  | nameとのユニークな組み合わせにする                                                                                                         | 
| 3   | 言語            | language         | string   |     |     |     | ○  | メソッドは、どれかの言語に属する。<br>`languages`テーブルは作らず、<br>選択肢はモデルでenumで持たせる                                      | 
| 4   | カテゴリー      | category         | string   |     |     |     | ○  | メソッドが何かのカテゴリーに属する、という概念を表す。<br>[例]<br>find_by: ActiveRecord<br>fileter : Array<br>each_with_index : Enumerable | 
| 5   | メソッド名      | name             | string   |     |     | ○  | ○  | user_idとのユニークな組み合わせにする                                                                                                      | 
| 6   | 動作内容        | operation_detail | text     |     |     | ○  | ○  |                                                                                                                                            | 
| 7   | 使用ケース      | use_case         | text     |     |     | ○  | ○  |                                                                                                                                            | 
| 8   | 覚えた          | remembered       | boolean  |     |     |     | ○  | メソッドを覚えたかどうかの管理フラグ                                                                                                       | 
| 9   | 公式サイトのurl | official_url     | string   |     |     |     |     | 公式サイトのURLを貼る                                                                                                                      | 
| 10  | 登録日          | created_at       | datetime |     |     |     | ○  |                                                                                                                                            | 
| 11  | 更新日          | updated_at       | datetime |     |     |     | ○  |                                                                                                                                            | 

<img width="560" alt="スクリーンショット 2023-06-27 12 22 27" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/086ff0a5-a912-4cee-924c-0b9f8b49045b">

**Comment by syo-tokeshi** [comment]
画面はそれに伴い、以下のようなUIに一部が変更されます
https://bootcamp.fjord.jp/products/16181

![スクリーンショット 2023-06-27 12 27 25](https://github.com/syo-tokeshi/method-quiz/assets/54713809/abda872a-6036-43db-8add-54663c2cc084)

![スクリーンショット 2023-06-27 12 27 56](https://github.com/syo-tokeshi/method-quiz/assets/54713809/42b6b33f-2d85-4e38-b181-a8879d010287)

![スクリーンショット 2023-06-27 12 28 22](https://github.com/syo-tokeshi/method-quiz/assets/54713809/98966e70-cfff-43a7-b0a6-c75c03cc8104)

![スクリーンショット 2023-06-27 12 28 54](https://github.com/syo-tokeshi/method-quiz/assets/54713809/0dd1cb5b-f7c3-4d17-a165-48ceae4da1ba)

**Comment by syo-tokeshi** [comment]
カテゴリーの機能は、
reactの`tagify`のライブラリを使って実装する予定です
https://codesandbox.io/s/tagify-react-wrapper-3m31v?file=/src/index.js

`whitelist`に、DBに保存されている`method.category`の値を利用し、入力補完を実現します。

サジェストは、１文字目の入力から、候補を提案するようにします
```js
dropdown: {
      enabled: 1 // a;ways show suggestions dropdown
    }
```

**Comment by syo-tokeshi** [comment]
また、`methods`テーブルが
- language
- category

を持っている事がおかしいのであれば、以下のようにテーブルを分割しようと思います
<img width="899" alt="スクリーンショット 2023-06-27 13 24 19" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/05593b80-4b8e-4ca8-8a58-c7a6706baa4f">

分割するのと、分割しないの、どちらが良いと思いますか？

考えてみたんですけど、
以下のようなメリット＆デメリットがあり、
分割しないほうを選んだ方が良い気がしています🙇‍♂️

[分割するメリット]
- 概念が明確になる
- 将来的に拡張しやすい
- テーブルの数が増えるので、就職活動で有利になる？（単純なものを作ってないと思われる）

[分割するデメリット]
- 拡張しないのであれば、分割しないほうが実装は楽
- YAGNIやGetting Real的にはこっちの方が良いと思う

**Comment by syo-tokeshi** [comment]
なぜテーブル名を変更したくなったかと言いますと、

私が用意した
- メソッド名
- カテゴリー
- 公式URL

が最初から作られているメソッドに対して、ユーザーが説明を加えて、クイズする

というアプリの仕様に変更したくなったからです🙇‍♂️

# 説明

管理者用のrubyのメソッドを登録する画面があり、私がこの画面から、メソッドを登録していきます(登録したら`ruby_methods`テーブルにデータが入る)

[index画面には登録したメソッド一覧と、新しいrubyのメソッドを登録するボタンが設置されている]
![スクリーンショット_2023-07-10_17_19_11](https://github.com/syo-tokeshi/method-quiz/assets/54713809/0a80f15b-7a27-4df0-89b8-6936fbfe760a)

[新しくメソッドを追加する所で、管理者である私はカテゴリーとメソッド名のみを入力]
![スクリーンショット 2023-07-10 17 24 52](https://github.com/syo-tokeshi/method-quiz/assets/54713809/7ac92dfa-5f15-4200-a181-32870853ba5e)

![スクリーンショット 2023-07-10 17 24 30](https://github.com/syo-tokeshi/method-quiz/assets/54713809/51dc616f-f43b-428f-95a1-355b329e18f3)

[登録すると自動でURLが生成される]
![スクリーンショット 2023-07-10 17 27 13](https://github.com/syo-tokeshi/method-quiz/assets/54713809/d3299c11-8719-44d5-931a-e0c1707031e4)

[一般ユーザーの、rubyメソッド一覧画面]
![スクリーンショット 2023-07-10 17 29 30](https://github.com/syo-tokeshi/method-quiz/assets/54713809/0aa6e2fe-6dda-41f1-94d3-98bd953f84cc)

[管理者(私)が登録したメソッドに対し、ユーザーが説明を入れる]
![スクリーンショット 2023-07-10 17 30 51](https://github.com/syo-tokeshi/method-quiz/assets/54713809/e4ade12e-f4b5-4fdb-a830-17b53fc770c3)

[リンクを踏むと公式に飛べる。ユーザーは正しい情報を確認しながらメソッドを覚えられる]
![スクリーンショット 2023-07-10 17 31 46](https://github.com/syo-tokeshi/method-quiz/assets/54713809/e4f7402e-4025-4d2b-afd3-a3361b8267c3)

**Comment by syo-tokeshi** [comment]
# 補足

## ユーザーが登録するrubyのメソッドの扱いについて

サービスリリース時、いくつかのメソッドを私の方で
- seedファイル
- `rails_admin_import`のgem
 
等を使い、データを流し込む予定です🙇‍♂️

また、サービスが継続していく中で、定期的に私の方で、
- WEBのインターフェイス 
- fly.ioに再push時
 
にメソッドを追加しようと思っています🙇‍♂️

[rails_admin_importのメソッドをcsv形式でインポートできる画面]
![スクリーンショット 2023-07-10 17 52 37](https://github.com/syo-tokeshi/method-quiz/assets/54713809/b0a75286-cacc-407f-9b4d-e5a45b053231)

**Comment by syo-tokeshi** [comment]
@yuuu 
お疲れ様です。
町田さんと話し合った結果、最終的にこのような設計になりました。
よろしいでしょうか？

# 新しいER図

<img width="890" alt="スクリーンショット 2023-07-12 22 19 18" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/61f8a380-9b14-4f12-a7b3-21ab2b6cab48">



# users

| No  | 論理名称   | 物理名称   | データ型 | PK  | UQ  | NN  | 備考                                                                                        | 
| --- | ---------- | ---------- | -------- | --- | --- | --- | ------------------------------------------------------------------------------------------- | 
| 1   | id         | id         | integer  | ○  | ○  | ○  | ユーザーのid                                                                                | 
| 2   | ユーザーid | uid        | string   |     | ○  | ○  | Githubのuser_id                                                                             | 
| 3   | ユーザー名 | name       | string   |     |     | ○  | Githubのユーザー名                                                                          | 
| 4   | 画像url    | avatar_url | string   |     |     | ○  | Githubのアバター写真                                                                        | 
| 5   | 管理者     | admin      | boolean  |     |     | ○  | 管理者の場合、`ruby_methods`へのアクセス権全てが手に入る。<br>一般ユーザーは閲覧 & 操作不可 | 
| 6   | 登録日     | created_at | datetime |     |     | ○  |                                                                                             | 
| 7   | 更新日     | updated_at | datetime |     |     | ○  |                                                                                             | 

# ruby_methods

| No  | 論理名称        | 物理名称     | データ型 | PK  | FK  | UQ  | NN  | 備考                                                                                                                   | 
| --- | --------------- | ------------ | -------- | --- | --- | --- | --- | ---------------------------------------------------------------------------------------------------------------------- | 
| 1   | id              | id           | integer  | ○  |     | ○  | ○  |                                                                                                                        | 
| 2   | メソッド名      | name         | string   |     |     |     | ○  | メソッドの名前。<br>違うクラス or モジュールで、同名メソッドがあるので、<br>nameとcategoryの組み合わせをユニークにする | 
| 3   | カテゴリー      | category     | integer  |     |     |     | ○  | メソッドは、どれかのカテゴリーに属する。<br>`categories`テーブルは作らず、<br>選択肢はモデルでenumで持たせる           | 
| 4   | 公式サイトのurl | official_url | string   |     |     |     | ○  | 公式サイトのURLを貼る。自動で入るようにするのでユニーク                                                                | 
| 5   | 登録日          | created_at   | datetime |     |     |     | ○  |                                                                                                                        | 
| 6   | 更新日          | updated_at   | datetime |     |     |     | ○  |                                                                                                                        | 

## user_ruby_methods

| user_ruby_methods |                |                |          |     |     |     |     |                                                                                                                                       | 
| ----------------- | -------------- | -------------- | -------- | --- | --- | --- | --- | ------------------------------------------------------------------------------------------------------------------------------------- | 
| No                | 論理名称       | 物理名称       | データ型 | PK  | FK  | UQ  | NN  | 備考                                                                                                                                  | 
| 1                 | id             | id             | integer  | ○  |     | ○  | ○  |                                                                                                                                       | 
| 2                 | user_id        | user_id        | integer  |     | ○  | ○  | ○  | usersテーブルのidを持つ。中間テーブルとしての役割                                                                                     | 
| 2                 | ruby_method_id | ruby_method_id | integer  |     | ○  | ○  | ○  | ruby_methodsテーブルのidを持つ。中間テーブルとしての役割                                                                              | 
| 2                 | 説明           | memo           | text     |     |     |     | ○  | 紐づいているrubyのメソッドの説明をする                                                                                                | 
| 7                 | 覚えた         | remembered     | integer  |     |     |     | ○  | integerだが、メソッドを覚えたかどうかの管理フラグ。<br>３択で管理する<br>0: not_yet (未着手)<br>1: yes (覚えた)<br>2: no (覚えてない) | 
| 8                 | 登録日         | created_at     | datetime |     |     |     | ○  |                                                                                                                                       | 
| 9                 | 更新日         | updated_at     | datetime |     |     |     | ○  |                                                                                                                                       |

**Comment by yuuu** [comment]
@syo-tokeshi 
見直しありがとうございます。いくつか確認させてください。

- `ruby_methods` の `category` という名前はどこかで使われている名前でしょうか？
    - ここはModuleまたはClassが該当すると思っていて、Ruby的にはClassもModuleなのでここは `module` という名前が適切なのかなと推測していました。
- `ruby_methods` の `category` は `enum` で管理するとのことですが、将来的に扱うクラス名が増えた場合はコードを修正するということでしょうか？
    - ここもテーブルにして、画面上から追加・削除できるようにする余地を残しておいた方が良い気がしています
    - クラスにもドキュメントが存在するので、将来的にここへのリンクを追加しようとするとどちらにせよテーブルが必要となりそうです
        - https://docs.ruby-lang.org/ja/latest/class/Array.html
- `user_ruby_methods` に「覚えた日」を表すカラムは不要でしょうか？

**Comment by syo-tokeshi** [comment]
- ruby_methods の category という名前はどこかで使われている名前でしょうか？

はい！使っておりました🙇‍♂️

- ここはModuleまたはClassが該当すると思っていて、Ruby的にはClassもModuleなのでここは module という名前が適切なのかなと推測していました。

かしこまりました🙇‍♂️
`category `から`module `という名前に変更します🙇‍♂️

- ruby_methods の category は enum で管理するとのことですが、将来的に扱うクラス名が増えた場合はコードを修正するということでしょうか？

はい、その運用を想定しておりました🙇‍♂️

- ここもテーブルにして、画面上から追加・削除できるようにする余地を残しておいた方が良い気がしています

こちらなんですが、
[本番環境にデプロイする際]
1. テーブルにする -> 初期の`category`のデータは、`seed`ファイルで最初に作成。その後、webの画面上から追加・削除する
1. enumにする -> webの画面上から追加・削除できないが、
- `seed`で流し込む必要がない 
- 今回のアプリではあくまで「よく使うRubyのメソッド」に限定するので、そこまでcategoryが増えない

といった条件なのですが、それでもテーブルを作成して管理した方が良さそうでしょうか？
私自身はenum慣れてしまったので、そのままが良いですが、プロ目線から見てそれは微妙だ、という事でありましたら、テーブルを作成したいと思います🙇‍♂️

- クラスにもドキュメントが存在するので、将来的にここへのリンクを追加しようとするとどちらにせよテーブルが必要となりそうです

今回は
- `Array#zip` https://docs.ruby-lang.org/ja/latest/method/Array/i/zip.html
- `String#slice!` https://docs.ruby-lang.org/ja/latest/method/String/i/slice=21.html

みたいなもののみを想定しているので、クラス自体へのリンクは想定していないです🙇‍♂️
yuuuさんの認識と違ってますでしょうか？😀

- user_ruby_methods に「覚えた日」を表すカラムは不要でしょうか？

「覚えた日」の概念をアプリで使う予定が、今の所ないです🙇‍♂️

1. クイズの選択条件
1. メソッド一覧の絞り込み機能

でも、「覚えた日」の概念は今の所いらなそうだなーと思ってます。
<img width="293" alt="スクリーンショット 2023-07-13 10 43 15" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/77050252-1774-4c9d-b039-ab0bc586d9c6">

<img width="279" alt="スクリーンショット 2023-07-13 10 43 28" src="https://github.com/syo-tokeshi/method-quiz/assets/54713809/8a8d2ba0-a276-42d5-933d-befd05f59b58">

**Comment by yuuu** [comment]
@syo-tokeshi 
回答ありがとうございます。

> それでもテーブルを作成して管理した方が良さそうでしょうか？
> 私自身は「enumにした方が簡単そうだ」と考えているのですが、どうでしょうか？

「今は仕様を最小限にしているから、このテーブル設計でもイケる」という判断はデータ設計をする上で本末転倒に感じました。「良いデータ設計」とは「仕様変更が発生しても対応しやすいテーブル構造」であり、ここではそれを目指している認識です。

自分はenumにした方が簡単とは思えないです。懸念点を列挙しますね。

- enumにした方が今の実装としては楽かもしれませんが、運用も含めて本当に楽になりますか？ 
    - 今の時点では頻繁にクラスを増やす予定はないとのことですが、増やす可能性は限りなく低いですか？
    - 増やす際、ソースコードを追記してデプロイしなおすのは大変ではないですか？
    - 今はクラスドキュメントへのリンクは不要とのことですが、ユーザーから「クラスドキュメントにもリンクがあると便利だなー」という要望が出てきたらどうします？
- 運用が始まってからenumをテーブルに変更するのは大変ではないですか？
    - 逆に、今の時点で「enumで作る場合」と「テーブルを作る場合」の実装コストはあまり変わらないのではないでしょうか？

> 「覚えた日」の概念をアプリで使う予定が今の所ないです🙇‍♂️

こちらは承知です。万が一必要となったとしてもカラムを増やすだけなので、こちらは現時点で追加しなくても大丈夫です 👍

**Comment by syo-tokeshi** [comment]
@yuuu 

> 「良いデータ設計」とは「仕様変更が発生しても対応しやすいテーブル構造」であり、ここではそれを目指している認識です。

理解しました🙇‍♂️
今回は、enumをテーブルに変更して作成します🙇‍♂️

- 拡張性
- 初期導入コスト

を考えると、テーブルで最初に作るのが無難そうですね😊
作った後に見える世界もあると思うので、それを楽しみにしつつテーブルにします😊

**Comment by syo-tokeshi** [comment]
新しいデータ設計を貼ります

# ruby_modules

| No  | 論理名称     | 物理名称   | データ型 | PK  | FK  | UQ  | NN  | 備考                                                             | 
| --- | ------------ | ---------- | -------- | --- | --- | --- | --- | ---------------------------------------------------------------- | 
| 1   | id           | id         | integer  | ○  |     | ○  | ○  |                                                                  | 
| 2   | モジュール名 | name       | string   |     |     | ○  | ○  | rubyのモジュールの名前。<br>rubyではクラスもモジュールに含まれる | 
| 3   | 登録日       | created_at | datetime |     |     |     | ○  |                                                                  | 
| 4   | 更新日       | updated_at | datetime |     |     |     | ○  |                                                                  |  

# ruby_methods

| No  | 論理名称        | 物理名称     | データ型 | PK  | FK  | UQ  | NN  | 備考                                         | 
| --- | --------------- | ------------ | -------- | --- | --- | --- | --- | -------------------------------------------- | 
| 1   | id              | id           | integer  | ○  |     | ○  | ○  |                                              | 
| 3   | モジュールid    | module_id    | integer  |     | ○  |     | ○  | rubyのメソッドは、どれかのモジュールに紐づく | 
| 2   | メソッド名      | name         | string   |     |     |     | ○  | メソッドの名前。                             | 
| 4   | 公式サイトのurl | official_url | string   |     |     |     | ○  | 公式サイトのURLを貼る。自動で入るようにする  | 
| 5   | 登録日          | created_at   | datetime |     |     |     | ○  |                                              | 
| 6   | 更新日          | updated_at   | datetime |     |     |     | ○  |                                              |

**Comment by yuuu** [comment]
修正ありがとうございました 🙏 データ設計も問題なさそうです！
